ModelBundle\Entity\Country:
    type: entity
    table: country
    indexes:
        name:
            columns:
                - name
    id:
        id:
            type: string
            nullable: false
            length: 3
            options:
                fixed: false
                comment: 'Código de país ISO alfa-2'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
    lifecycleCallbacks: {  }
