ModelBundle\Entity\Document:
    type: entity
    table: document
    indexes:
        fk_document_entity1_idx:
            columns:
                - entity_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
                comment: 'File ID.'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        filename:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                comment: 'Name of the file with no path components. This may differ from the basename of the URI if the file is renamed to avoid overwriting an existing file.'
                default: ''
        uri:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                comment: 'The URI to access the file (either local or remote).'
                default: ''
        filemime:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                comment: 'The file’s MIME type.'
                default: ''
        filesize:
            type: bigint
            nullable: false
            options:
                unsigned: true
                comment: 'The size of the file in bytes.'
                default: '0'
        status:
            type: boolean
            nullable: false
            options:
                comment: 'A field indicating the status of the file. Two status are defined in core: temporary (0) and permanent (1). Temporary files older than DRUPAL_MAXIMUM_TEMP_FILE_AGE will be removed during a cron run.'
                default: '0'
        timestamp:
            type: integer
            nullable: false
            options:
                unsigned: true
                comment: 'UNIX timestamp for when the file was added.'
                default: '0'
        type:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                comment: 'The ENGINE of this file.'
                default: undefined
        field:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
    manyToOne:
        entity:
            targetEntity: Entity
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                entity_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
