ModelBundle\Entity\Extension:
    type: entity
    table: extension
    indexes:
        fk_extension_accord1_idx:
            columns:
                - accord_id
        fk_extension_service_request1_idx:
            columns:
                - service_request_id
        fk_extension_entity1_idx:
            columns:
                - id
    id: {  }
    fields:
        dateStart:
            type: date
            nullable: true
            column: date_start
        dateEnd:
            type: date
            nullable: true
            column: date_end
        description:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        signerConsultant:
            type: blob
            nullable: true
            length: 65535
            options:
                fixed: false
            column: signer_consultant
    manyToOne:
        accord:
            targetEntity: Accord
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                accord_id:
                    referencedColumnName: id
            orphanRemoval: false
        serviceRequest:
            targetEntity: ServiceRequest
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                service_request_id:
                    referencedColumnName: id
            orphanRemoval: false
    oneToOne:
        id:
            targetEntity: Entity
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
